import Mathlib.MeasureTheory.Measure.Hausdorff
import FormalizingGMT.«Project Versions».Measures.Basic
import FormalizingGMT.«Project Versions».Measures.Thm1_7
import FormalizingGMT.«Project Versions».Densities.Basic

open scoped BigOperators Real Nat Classical Pointwise
open MeasureTheory MeasureTheory.OuterMeasure Set
set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128
set_option relaxedAutoImplicit false
set_option autoImplicit false
set_option grind.warning false
/-!
## Hausdorff content
-/
/-- The `s`-dimensional **Hausdorff content** of a set `E` with covers of diameter ≤ `δ`.
Empty members of a cover contribute zero to the sum. -/
noncomputable def hausdorffContent
    {X : Type*} [EMetricSpace X] (s : ℝ) (δ : ENNReal) (E : Set X) : ENNReal :=
  ⨅ (t : ℕ → Set X) (_ : E ⊆ ⋃ i, t i) (_ : ∀ i, Metric.ediam (t i) ≤ δ),
    ∑' i, ⨆ (_ : (t i).Nonempty), (Metric.ediam (t i)) ^ s

/-- Unrestricted Hausdorff content `H^s_∞(E)`: infimum over all countable covers,
with no diameter bound. Empty members of a cover contribute zero to the sum. -/
noncomputable def hausdorffContentInfty
    {X : Type*} [EMetricSpace X] (s : ℝ) (E : Set X) : ENNReal :=
  ⨅ (t : ℕ → Set X) (_ : E ⊆ ⋃ i, t i),
    ∑' i, ⨆ (_ : (t i).Nonempty), (Metric.ediam (t i)) ^ s

/-!
## Regularity of the restricted Hausdorff measure on a locally compact Hausdorff space
-/

section LocallyCompact

variable {X : Type*} [PseudoMetricSpace X] [LocallyCompactSpace X] [T2Space X]

-- A Hausdorff pseudometric space is a genuine metric space (points at distance `0` coincide),
-- hence an extended metric space, which is the setting in which the Hausdorff measure `μH[s]`
-- is defined.  The metric, and therefore the topology, is unchanged.
attribute [local instance] MetricSpace.ofT0PseudoMetricSpace

/-- The `s`-dimensional Hausdorff measure `μH[s]` on `X` is built from the metric structure of
`X`; the measurable space structure it is defined with respect to is the Borel σ-algebra of `X`,
i.e. the σ-algebra generated by the open sets. -/
local instance hausdorffMeasurableSpace : MeasurableSpace X := borel X

omit [LocallyCompactSpace X] [T2Space X] in
/-- **The `s`-dimensional Hausdorff measure admits the Borel σ-algebra as its measurable space.**
With the measurable space structure `hausdorffMeasurableSpace` (the σ-algebra generated by the
open sets of `X`), `X` is a `BorelSpace`, which is exactly the hypothesis needed to define and
reason about `μH[s]` as a measure. -/
lemma hausdorffMeasure_borelSpace : BorelSpace X := ⟨rfl⟩

attribute [local instance] hausdorffMeasure_borelSpace

/-- **The restricted Hausdorff measure is regular.**  Let `X` be a locally compact, Hausdorff,
second countable pseudometric space, equipped with its Borel σ-algebra (see
`hausdorffMeasure_borelSpace`), let `s ≥ 0`, and let `E ⊆ X` be Carathéodory measurable for the
`s`-dimensional Hausdorff outer measure with `μH[s] E < ∞`.  Then the restricted measure
`(μH[s]).restrict E` belongs to Mathlib's class `MeasureTheory.Measure.Regular`: it is outer
regular by open sets and inner regular by compact sets on open sets.

The proof is an application of `BorelRegularOuterMeasure.restrict_isRadon`.  As in that theorem,
a countability assumption is needed (local compactness and the Hausdorff property alone do not
suffice for regularity), and we use second countability.  The hypotheses `0 ≤ s` and the
Carathéodory measurability of `E` are part of the standard statement but are not needed for the
conclusion, which only uses the finiteness of `μH[s] E`. -/
instance HausdorffRestrict.toRadonOuterMeasure [SecondCountableTopology X]
    (s : ℝ) (hs : 0 ≤ s) (E : Set X)
    (hE_meas : MeasurableSet[
      (OuterMeasure.mkMetric (X := X) (fun r => r ^ s)).caratheodory] E)
    (hE_fin : MeasureTheory.Measure.hausdorffMeasure s E < ⊤) :
    ((MeasureTheory.Measure.hausdorffMeasure s : MeasureTheory.Measure X).restrict E).Regular :=
  BorelRegularOuterMeasure.restrict_isRadon E hE_fin

end LocallyCompact

  /-!

## Restricting the diameter bound to `≥ diam E` does not change the content

If `E` has diameter `≤ δ`, then the `δ`-restricted Hausdorff content of `E` agrees with the
unrestricted Hausdorff content `H^s_∞(E)`.  This is the standard fact that the Hausdorff content
`H^s_δ` stabilises once `δ` exceeds the diameter of the set being measured.
-/

/-- For a strictly positive exponent, the `Nonempty`-guarded summand used in `hausdorffContent`
coincides with the plain summand used in `hausdorffContentInfty`: the only place they could
differ is on the empty set, where both are `0` when `s > 0`. -/
lemma hausdorffContent_summand_eq {X : Type*} [EMetricSpace X] {s : ℝ} (hs : 0 < s)
    (U : Set X) :
    (⨆ (_ : U.Nonempty), (Metric.ediam U) ^ s) = (Metric.ediam U) ^ s := by
  by_cases h : U.Nonempty
  · rw [iSup_pos h]
  · rw [Set.not_nonempty_iff_eq_empty] at h
    rw [iSup_neg (by simp [h]), h, Metric.ediam_empty, ENNReal.zero_rpow_of_pos hs,
      ENNReal.bot_eq_zero]

/-- The unrestricted Hausdorff content is at most the `δ`-restricted content, because dropping
the diameter constraint enlarges the family of admissible covers. -/
lemma hausdorffContentInfty_le_hausdorffContent {X : Type*} [EMetricSpace X]
    (s : ℝ) (δ : ENNReal) (E : Set X) :
    hausdorffContentInfty s E ≤ hausdorffContent s δ E := by
  unfold hausdorffContent hausdorffContentInfty
  refine le_iInf fun t => le_iInf fun hcov => le_iInf fun _ => ?_
  exact iInf₂_le t hcov

/-- The `δ`-restricted Hausdorff content is at most the unrestricted content, provided `E` has
diameter at most `δ`. -/
lemma hausdorffContent_le_hausdorffContentInfty {X : Type*} [EMetricSpace X] {s : ℝ}
    (hs : 0 ≤ s) {δ : ENNReal} {E : Set X} (hE : Metric.ediam E ≤ δ) :
    hausdorffContent s δ E ≤ hausdorffContentInfty s E := by
  unfold hausdorffContent hausdorffContentInfty
  refine le_iInf fun t => le_iInf fun hcov => ?_
  set t' : ℕ → Set X := fun i => t i ∩ E with ht'
  have hcov' : E ⊆ ⋃ i, t' i := by
    intro x hx
    obtain ⟨i, hxi⟩ := Set.mem_iUnion.mp (hcov hx)
    exact Set.mem_iUnion.mpr ⟨i, hxi, hx⟩
  have hdiam' : ∀ i, Metric.ediam (t' i) ≤ δ := by
    intro i
    exact le_trans (Metric.ediam_mono (by simp [ht', Set.inter_subset_right])) hE
  refine le_trans (iInf₂_le t' hcov') ?_
  refine le_trans (iInf_le _ hdiam') ?_
  refine ENNReal.tsum_le_tsum fun i => ?_
  apply iSup_le
  intro hti
  have hti' : (t i).Nonempty := hti.mono (by simp [ht', Set.inter_subset_left])
  refine le_iSup_of_le hti' ?_
  exact ENNReal.rpow_le_rpow
    (Metric.ediam_mono (by simp [ht', Set.inter_subset_left])) hs

/-- **Stabilisation of the Hausdorff content.** If `E` has `ediam E ≤ δ` and `s ≥ 0`, then its
`δ`-restricted Hausdorff content equals its unrestricted Hausdorff content. The hypothesis
`0 < δ` is retained in the standard positive-scale statement, though the proof does not need it. -/
theorem hausdorffContent_eq_hausdorffContentInfty_of_ediam_le {X : Type*} [EMetricSpace X]
    {s : ℝ} (hs : 0 ≤ s) {δ : ENNReal} (hδ : 0 < δ) {E : Set X} (hE : Metric.ediam E ≤ δ) :
    hausdorffContent s δ E = hausdorffContentInfty s E :=
  le_antisymm (hausdorffContent_le_hausdorffContentInfty hs hE)
    (hausdorffContentInfty_le_hausdorffContent s δ E)

/-!
## Hausdorff content is dominated by the Hausdorff measure
-/
/-- The `δ`-approximating Hausdorff content is at most the full Hausdorff measure:
    `H^s_δ(E) ≤ H^s(E)` for any diameter bound `δ > 0`. This holds because the Hausdorff
    measure is the supremum over all `r > 0` of the `r`-restricted contents
    (`MeasureTheory.Measure.hausdorffMeasure_apply`), and `hausdorffContent s δ` is exactly the
    term of that supremum at `r = δ`. -/
lemma hausdorffContent_le_hausdorffMeasure {X : Type*} [EMetricSpace X]
    [MeasurableSpace X] [BorelSpace X]
    {s : ℝ} {δ : ENNReal} (hδ : 0 < δ) (E : Set X) :
    hausdorffContent s δ E ≤ MeasureTheory.Measure.hausdorffMeasure s E := by
  rw [MeasureTheory.Measure.hausdorffMeasure_apply]
  exact le_iSup₂_of_le δ hδ le_rfl
