/-
Copyright (c) 2026 FormalizingGMT contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: FormalizingGMT contributors
-/

import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Analysis.SpecialFunctions.Pow.Continuity
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Mathlib.Topology.Order.LiminfLimsup
import Mathlib.Topology.Order.OrderClosed
import Mathlib.Topology.Algebra.Order.LiminfLimsup
import Mathlib.Tactic

/-!
# Measures on a Borel space, viewed as outer measures

This instructional file explains how Borel regularity of a measure, viewed as an outer measure,
is obtained in Mathlib. None of its declarations are used elsewhere in the project.

Let `X` be a topological space whose measurable structure is the Borel σ-algebra
(`BorelSpace X`), and let `μ` be a measure on `X`. Viewing `μ` as an outer measure
(`μ.toOuterMeasure`, which agrees with `μ` on every set), we prove:

1. every measurable, equivalently Borel, set is Carathéodory measurable for `μ.toOuterMeasure`;
2. every subset `E ⊆ X` is contained in a Borel set `F` with `μ F = μ E`.

Together these say that a measure on a Borel space is a Borel regular outer measure.
-/

open scoped BigOperators Real Nat Pointwise
open MeasureTheory MeasureTheory.Measure Metric Set Filter Topology ENNReal

variable {X : Type*} [MeasurableSpace X] [TopologicalSpace X] [BorelSpace X] {μ : Measure X}

omit [TopologicalSpace X] [BorelSpace X] in
/-- **Property 1.** Every measurable set is Carathéodory measurable for the outer measure
associated to a measure `μ`. -/
theorem measurableSet_caratheodory_toOuterMeasure {s : Set X} (hs : MeasurableSet s) :
    MeasurableSet[μ.toOuterMeasure.caratheodory] s := by
  rw [OuterMeasure.isCaratheodory_iff_le]
  intro t
  simp only [Measure.toOuterMeasure_apply]
  exact (measure_inter_add_sdiff t hs).le

omit [TopologicalSpace X] [BorelSpace X] in
/-- **Property 1, restated.** The ambient σ-algebra of `X` is contained in the σ-algebra of
Carathéodory-measurable sets of the outer measure `μ.toOuterMeasure`. -/
theorem measurableSpace_le_caratheodory :
    ‹MeasurableSpace X› ≤ (μ.toOuterMeasure).caratheodory := fun _ hs =>
  measurableSet_caratheodory_toOuterMeasure hs

/-- Every Borel set is Carathéodory measurable for `μ.toOuterMeasure`; here "Borel" is
spelled out as measurability for the σ-algebra `borel X` generated by the open sets. -/
theorem borel_le_caratheodory :
    borel X ≤ (μ.toOuterMeasure).caratheodory := by
  rw [← BorelSpace.measurable_eq (α := X)]
  exact measurableSpace_le_caratheodory

/-- **Property 2.** Every subset `E` of `X` is contained in a Borel set `F` with
`μ F = μ E`. -/
theorem exists_borel_superset_measure_eq (E : Set X) :
    ∃ F : Set X, MeasurableSet[borel X] F ∧ E ⊆ F ∧ μ F = μ E := by
  obtain ⟨F, hEF, hF, hmeas⟩ := exists_measurable_superset μ E
  refine ⟨F, ?_, hEF, hmeas⟩
  rwa [← BorelSpace.measurable_eq (α := X)]
