/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4a4c54c2-66d6-4726-b24e-e1ab9bfed4d9

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We proved a series of lemmas leading to the result that the set of points where the "density" (proxied by `E_delta_tau`) is consistently low has Hausdorff measure zero.
Specifically, we proved:
1. `lemma_1c`: A contraction inequality for the Hausdorff content of `E_delta_tau`.
2. `lemma_1d`: If the Hausdorff content of `E_delta_tau` is finite, it must be zero.
3. `hContent_zero_mono`: Monotonicity of zero content with respect to scale.
4. `hContent_zero_implies_hausdorffMeasure_zero`: Zero content implies zero measure.
5. `lemma_1e`: If `E` has finite measure, then `E_delta_tau` has measure zero.
6. `measure_E_star_tau_eq_zero`: The set `E_star_tau` (union of `E_delta_tau` over scales) has measure zero.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of Hausdorff content at scale delta.
-/
def hausdorffContent {X : Type*} [EMetricSpace X] (d : ℝ) (δ : ℝ) (s : Set X) : ENNReal :=
  ⨅ (t : ℕ → Set X) (_ : s ⊆ ⋃ n, t n) (_ : ∀ n, EMetric.diam (t n) ≤ ENNReal.ofReal δ),
    ∑' n, (EMetric.diam (t n)) ^ d

/-
Definition of the set E(δ, τ).
-/
def E_delta_tau {X : Type*} [EMetricSpace X] [MeasurableSpace X] [BorelSpace X]
    (E : Set X) (s : ℝ) (δ : ℝ) (τ : ℝ) : Set X :=
  {x ∈ E | ∀ C, x ∈ C → EMetric.diam C ≤ ENNReal.ofReal δ →
    MeasureTheory.Measure.hausdorffMeasure s (C ∩ E) ≤ ENNReal.ofReal τ * (EMetric.diam C) ^ s}

/-
We first show that if $0<\delta\leq\delta'$, then $E(\delta',1-\delta')\subset E(\delta,1-\delta)$.
-/
lemma E_delta_tau_nested {X : Type*} [EMetricSpace X] [MeasurableSpace X] [BorelSpace X]
    {E : Set X} {s : ℝ} {δ δ' : ℝ} (hδ : 0 < δ) (hδ' : δ ≤ δ') :
    E_delta_tau E s δ' (1 - δ') ⊆ E_delta_tau E s δ (1 - δ) := by
      intro x hx;
      refine' ⟨ hx.1, fun C hx' hx'' => _ ⟩;
      refine' le_trans ( hx.2 C hx' _ ) _;
      · exact le_trans hx'' ( ENNReal.ofReal_le_ofReal hδ' );
      · gcongr

/-
Hausdorff content is less than or equal to Hausdorff measure.
-/
def hContent {X : Type*} [EMetricSpace X] (d : ℝ) (δ : ℝ) (s : Set X) : ENNReal :=
  ⨅ (t : ℕ → Set X) (_ : s ⊆ ⋃ n, t n) (_ : ∀ n, EMetric.diam (t n) ≤ ENNReal.ofReal δ),
    ∑' n, ⨆ (_ : (t n).Nonempty), (EMetric.diam (t n)) ^ d

lemma hContent_le_hausdorffMeasure {X : Type*} [EMetricSpace X] [MeasurableSpace X] [BorelSpace X]
    {d : ℝ} {δ : ℝ} {s : Set X} (hδ : 0 < δ) :
    hContent d δ s ≤ MeasureTheory.Measure.hausdorffMeasure d s := by
      -- By definition of the Hausdorff measure, we know that for any $r > 0$, the content at scale $r$ is less than or equal to the Hausdorff measure. Therefore, we can choose $r = \delta$.
      have h_content_le_measure : ∀ r > 0, hContent d r s ≤ (MeasureTheory.Measure.hausdorffMeasure d) s := by
        intro r hr;
        rw [ MeasureTheory.Measure.hausdorffMeasure_apply ];
        refine' le_ciSup _ ( ENNReal.ofReal r ) |> le_trans _;
        · simp +decide [ hContent, ENNReal.ofReal_pos, hr ];
        · exact?;
      exact h_content_le_measure δ hδ

/-
Covering estimate for E(delta, tau).
-/
lemma lemma_1a_fix {X : Type*} [EMetricSpace X] [MeasurableSpace X] [BorelSpace X]
    (E : Set X) (s : ℝ) (δ : ℝ) (τ : ℝ) (hδ : 0 < δ) (hτ : 0 < τ) (hτ1 : τ < 1)
    (C : ℕ → Set X)
    (h_cover : E_delta_tau E s δ τ ⊆ ⋃ i, C i)
    (h_diam : ∀ i, EMetric.diam (C i) ≤ ENNReal.ofReal δ)
    (h_inter : ∀ i, (C i ∩ E_delta_tau E s δ τ).Nonempty) :
    hContent s δ (E_delta_tau E s δ τ) ≤ ENNReal.ofReal τ * ∑' i, (EMetric.diam (C i)) ^ s := by
      have := h_inter 0;
      revert this;
      -- Since $x_i \in C_i$, we have $C_i \subset B(x_i,\operatorname{diam} C_i)$.
      intro h_nonempty
      have h_subset : ∀ i, MeasureTheory.Measure.hausdorffMeasure s (C i ∩ E_delta_tau E s δ τ) ≤ ENNReal.ofReal τ * (EMetric.diam (C i)) ^ s := by
        intro i
        obtain ⟨x_i, hx_i⟩ : ∃ x_i, x_i ∈ C i ∩ E_delta_tau E s δ τ := h_inter i;
        have := hx_i.2;
        exact le_trans ( MeasureTheory.measure_mono ( Set.inter_subset_inter_right _ ( show E_delta_tau E s δ τ ⊆ E from fun x hx => hx.1 ) ) ) ( this.2 _ hx_i.1 ( h_diam i ) );
      -- Using sub-additivity of $\mathcal{H}^s_\delta$, it follows that
      have h_subadd : MeasureTheory.Measure.hausdorffMeasure s (E_delta_tau E s δ τ) ≤ ∑' i, MeasureTheory.Measure.hausdorffMeasure s (C i ∩ E_delta_tau E s δ τ) := by
        refine' le_trans ( MeasureTheory.measure_mono ( show E_delta_tau E s δ τ ⊆ ⋃ i, ( C i ∩ E_delta_tau E s δ τ ) from fun x hx => by have := h_cover hx; aesop ) ) ( MeasureTheory.measure_iUnion_le _ );
      refine' le_trans ( hContent_le_hausdorffMeasure hδ ) _;
      exact h_subadd.trans ( by rw [ ← ENNReal.tsum_mul_left ] ; exact ENNReal.tsum_le_tsum h_subset )

/-
If E(delta, tau) is non-empty and tau < 1, then s != 0.
-/
lemma s_ne_zero_of_mem_E_delta_tau {X : Type*} [EMetricSpace X] [MeasurableSpace X] [BorelSpace X]
    {E : Set X} {s δ τ : ℝ} (hτ : τ < 1) {x : X} (hx : x ∈ E_delta_tau E s δ τ) : s ≠ 0 := by
      intro hs
      have := hx.2 {x} (Set.mem_singleton x) (by
      simp +decide [ EMetric.diam_singleton ])
      simp [hs] at this
      skip
      generalize_proofs at *; (
      -- Since $x \in E$, we have $\{x\} \cap E = \{x\}$.
      have h_inter : {x} ∩ E = {x} := by
        exact Set.inter_eq_left.mpr ( by simp +decide [ hx.1 ] )
      rw [h_inter] at this
      simp at this
      generalize_proofs at *; (
      linarith))

/-
Checking Encodable instances.
-/
#synth Encodable ℕ
#synth Encodable {n : ℕ // n > 5}

/-
Definition of modified cover.
-/
def modified_cover {X : Type*} [EMetricSpace X] (U : ℕ → Set X) (E : Set X) (x : X) (n : ℕ) : Set X :=
  if (U n ∩ E).Nonempty then U n else {x}

/-
The modified cover covers the intersection of E and the original cover.
-/
lemma modified_cover_subset {X : Type*} [EMetricSpace X] (U : ℕ → Set X) (E : Set X) (x : X) :
    E ∩ ⋃ n, U n ⊆ ⋃ k, modified_cover U E x k := by
      -- Take any $y \in E \cap \bigcup U_n �$.� Then $y \in E$ and there exists $k$ such that $ �y� \in U_k$.
      intro y hy
      obtain ⟨k, hk⟩ : ∃ k, y ∈ U k := by
        aesop;
      simp_all +decide [ Set.ext_iff, modified_cover ];
      exact ⟨ k, by rw [ if_pos ⟨ y, hk, hy.1 ⟩ ] ; exact hk ⟩

/-
The modified cover intersects E.
-/
lemma modified_cover_inter_nonempty {X : Type*} [EMetricSpace X] (U : ℕ → Set X) (E : Set X) (x : X) (hx : x ∈ E) :
    ∀ k, (modified_cover U E x k ∩ E).Nonempty := by
      unfold modified_cover;
      aesop

/-
The diameter of each set in the modified cover is bounded by the supremum of diameters in the original cover.
-/
lemma modified_cover_diam_le {X : Type*} [EMetricSpace X] (U : ℕ → Set X) (E : Set X) (x : X) (k : ℕ) :
    EMetric.diam (modified_cover U E x k) ≤ ⨆ n, EMetric.diam (U n) := by
      unfold modified_cover;
      split_ifs <;> [ exact le_ciSup ( show BddAbove ( Set.range fun n => EMetric.diam ( U n ) ) from ⟨ ⊤, Set.forall_mem_range.2 fun n => le_top ⟩ ) k; exact le_trans ( by simp +decide ) ( le_ciSup ( show BddAbove ( Set.range fun n => EMetric.diam ( U n ) ) from ⟨ ⊤, Set.forall_mem_range.2 fun n => le_top ⟩ ) k ) ]

/-
The sum of powers of diameters of the modified cover is less than or equal to that of the original cover.
-/
lemma modified_cover_sum_le {X : Type*} [EMetricSpace X] {s : ℝ} (hs : 0 < s)
    (U : ℕ → Set X) (E : Set X) (x : X) :
    ∑' k, (EMetric.diam (modified_cover U E x k))^s ≤ ∑' n, (EMetric.diam (U n))^s := by
      apply_rules [ ENNReal.tsum_le_tsum ];
      intro n; by_cases h : Set.Nonempty ( U n ∩ E ) <;> simp +decide [ *, modified_cover ] ;

/-
Helper lemma for 1c: bound for a specific cover.
-/
lemma lemma_1c_helper {X : Type*} [EMetricSpace X] [MeasurableSpace X] [BorelSpace X]
    (E : Set X) (s : ℝ) (δ : ℝ) (τ : ℝ) (hs : 0 < s)
    (h_impl : ∀ (C : ℕ → Set X),
      (E_delta_tau E s δ τ ⊆ ⋃ i, C i) →
      (∀ i, EMetric.diam (C i) ≤ ENNReal.ofReal δ) →
      (∀ i, (C i ∩ E_delta_tau E s δ τ).Nonempty) →
      hContent s δ (E_delta_tau E s δ τ) ≤ ENNReal.ofReal τ * ∑' i, (EMetric.diam (C i)) ^ s)
    (C : ℕ → Set X)
    (h_cover : E_delta_tau E s δ τ ⊆ ⋃ i, C i)
    (h_diam : ∀ i, EMetric.diam (C i) ≤ ENNReal.ofReal δ)
    (x : X) (hx : x ∈ E_delta_tau E s δ τ) :
    hContent s δ (E_delta_tau E s δ τ) ≤ ENNReal.ofReal τ * ∑' i, (EMetric.diam (C i)) ^ s := by
      -- Let's define the modified cover $C'$.
      set C' : ℕ → Set X := fun i => modified_cover C (E_delta_tau E s δ τ) x i;
      refine' le_trans ( h_impl C' _ _ _ ) ( mul_le_mul_left' ( modified_cover_sum_le hs C _ _ ) _ );
      · exact fun y hy => modified_cover_subset C _ _ |> fun h => h <| Set.mem_inter hy ( h_cover hy );
      · intro i;
        refine' le_trans ( modified_cover_diam_le _ _ _ _ ) _;
        exact ciSup_le h_diam;
      · exact?

/-
The sum of powers of diameters is equal to the term used in hContent definition.
-/
lemma sum_eq_content_term {X : Type*} [EMetricSpace X] {s : ℝ} (hs : 0 < s) (C : ℕ → Set X) :
    ∑' i, (EMetric.diam (C i)) ^ s = ∑' i, ⨆ (_ : (C i).Nonempty), (EMetric.diam (C i)) ^ s := by
      refine' tsum_congr fun i => _;
      by_cases hi : ( C i ).Nonempty <;> simp +decide [ hi ];
      simp_all +decide [ Set.not_nonempty_iff_eq_empty.mp hi ]


/-
The Hausdorff content of E(delta, tau) satisfies a contraction inequality.
-/
lemma lemma_1c {X : Type*} [EMetricSpace X] [MeasurableSpace X] [BorelSpace X]
    (E : Set X) (s : ℝ) (δ : ℝ) (τ : ℝ) (hδ : 0 < δ) (hτ : 0 < τ) (hτ1 : τ < 1) (hs : 0 < s) :
    hContent s δ (E_delta_tau E s δ τ) ≤ ENNReal.ofReal τ * hContent s δ (E_delta_tau E s δ τ) := by
      by_cases h : E_delta_tau E s δ τ = ∅;
      · simp +decide [ h, hContent ];
        refine' le_trans _ ( mul_le_mul_left' ( le_iInf fun t => le_iInf fun ht => _ ) _ );
        rotate_left;
        exact 0;
        · exact zero_le _;
        · refine' le_trans ( ciInf_le _ ( fun _ => ∅ ) ) _ <;> simp +decide;
      · -- By definition of Hausdorff content, it suffices to show that for any cover $C$ of $E_{\delta, \tau}$ with diameters $\le \delta$, we have $hContent \le \tau \sum diam(C_i)^s$.
        suffices h_suff : ∀ (C : ℕ → Set X),
            (E_delta_tau E s δ τ ⊆ ⋃ i, C i) →
            (∀ i, EMetric.diam (C i) ≤ ENNReal.ofReal δ) →
            hContent s δ (E_delta_tau E s δ τ) ≤ ENNReal.ofReal τ * ∑' i, (EMetric.diam (C i)) ^ s by
              refine' le_trans _ ( mul_le_mul_left' ( le_iInf fun C => _ ) _ );
              rotate_left;
              exact hContent s δ ( E_delta_tau E s δ τ );
              · refine' le_iInf fun hC => le_iInf fun hC' => _;
                refine' le_trans ( h_suff C hC hC' ) _;
                rw [ ← ENNReal.tsum_mul_left ];
                refine' ENNReal.tsum_le_tsum fun n => _;
                by_cases hn : ( C n ).Nonempty <;> simp +decide [ hn ];
                · exact mul_le_of_le_one_left ( by positivity ) ( ENNReal.ofReal_le_one.mpr hτ1.le );
                · simp_all +decide [ Set.not_nonempty_iff_eq_empty.mp hn ];
              · refine' le_trans ( le_of_eq _ ) ( mul_le_mul_left' ( le_iInf fun C => _ ) _ );
                rotate_left;
                exact ( ENNReal.ofReal τ ) ⁻¹ * hContent s δ ( E_delta_tau E s δ τ );
                · by_cases hC : E_delta_tau E s δ τ ⊆ ⋃ n, C n <;> by_cases hC' : ∀ n, EMetric.diam ( C n ) ≤ ENNReal.ofReal δ <;> simp +decide [ hC, hC' ];
                  rw [ ENNReal.inv_mul_le_iff ];
                  · convert h_suff C hC hC' using 1;
                    congr! 2;
                    ext n; by_cases hn : ( C n ).Nonempty <;> simp +decide [ hn ] ;
                    rw [ show C n = ∅ by exact Set.not_nonempty_iff_eq_empty.mp hn, EMetric.diam_empty, ENNReal.zero_rpow_of_pos hs ];
                  · positivity;
                  · exact ENNReal.ofReal_ne_top;
                · rw [ ← mul_assoc, ENNReal.mul_inv_cancel ( by aesop ) ( by aesop ), one_mul ];
        -- Let $x \in E_{\delta, \tau}$.
        obtain ⟨x, hx⟩ : ∃ x, x ∈ E_delta_tau E s δ τ := by
          exact Set.nonempty_iff_ne_empty.2 h;
        intro C hC hC';
        apply lemma_1c_helper;
        exacts [ hs, fun C hC hC' hC'' => lemma_1a_fix E s δ τ hδ hτ hτ1 C hC hC' hC'', hC, hC', hx ]

/-
If the Hausdorff content is finite, it must be zero.
-/
lemma lemma_1d {X : Type*} [EMetricSpace X] [MeasurableSpace X] [BorelSpace X]
    (E : Set X) (s : ℝ) (δ : ℝ) (τ : ℝ) (hδ : 0 < δ) (hτ : 0 < τ) (hτ1 : τ < 1) (hs : 0 < s)
    (h_fin : hContent s δ (E_delta_tau E s δ τ) ≠ ⊤) :
    hContent s δ (E_delta_tau E s δ τ) = 0 := by
      -- By `lemma_1c`, we have $hContent \le \tau * hContent$.
      have h_le : (hContent s δ (E_delta_tau E s δ τ)) ≤ ENNReal.ofReal τ * (hContent s δ (E_delta_tau E s δ τ)) := by
        convert lemma_1c E s δ τ hδ hτ hτ1 hs using 1;
      by_cases h : hContent s δ ( E_delta_tau E s δ τ ) = 0 <;> simp_all +decide [ ENNReal.ofReal ];
      rw [ ← ENNReal.toReal_le_toReal ] at h_le <;> norm_num at *;
      · exact absurd h_le ( by rw [ max_eq_left hτ.le ] ; nlinarith [ show 0 < ( hContent s δ ( E_delta_tau E s δ τ ) |> ENNReal.toReal ) from ENNReal.toReal_pos h h_fin ] );
      · exact h_fin;
      · exact ENNReal.mul_ne_top ENNReal.coe_ne_top h_fin

/-
If the Hausdorff content is zero at some scale, it is zero at any scale.
-/
lemma hContent_zero_mono {X : Type*} [EMetricSpace X]
    {s : ℝ} {δ δ' : ℝ} {E : Set X} (hs : 0 < s) (hδ : 0 < δ) (hδ' : 0 < δ')
    (h : hContent s δ E = 0) :
    hContent s δ' E = 0 := by
      refine' le_antisymm ( le_trans ( le_of_eq ( Eq.symm _ ) ) ( le_of_forall_gt_imp_ge_of_dense _ ) ) bot_le;
      exact?;
      intro ε hε;
      -- Choose η such that η < ε and η^(1/s) ≤ δ'.
      obtain ⟨η, hη₁, hη₂⟩ : ∃ η : ENNReal, 0 < η ∧ η < ε ∧ η^(1 / s) ≤ ENNReal.ofReal δ' := by
        -- Since $\eta^{1/s} \leq \delta'$, we can choose $\eta$ such that $\eta \leq (\delta')^s$.
        obtain ⟨η, hη₁, hη₂⟩ : ∃ η : ENNReal, 0 < η ∧ η < ε ∧ η ≤ (ENNReal.ofReal δ') ^ s := by
          by_cases hη : ENNReal.ofReal δ' ^ s < ε;
          · exact ⟨ ENNReal.ofReal δ' ^ s, by positivity, hη, le_rfl ⟩;
          · rcases ENNReal.lt_iff_exists_nnreal_btwn.mp hε with ⟨ η, hη₁, hη₂ ⟩;
            exact ⟨ η, by simpa using hη₁, hη₂, le_trans ( by simpa using hη₂.le ) ( le_of_not_gt hη ) ⟩;
        refine' ⟨ η, hη₁, hη₂.1, _ ⟩;
        exact le_trans ( ENNReal.rpow_le_rpow hη₂.2 ( by positivity ) ) ( by rw [ ← ENNReal.rpow_mul, mul_one_div_cancel hs.ne', ENNReal.rpow_one ] );
      -- Since `hContent s δ E = 0`, for any `η > 0`, there exists a cover `{U_i}` such that `diam(U_i) ≤ δ` and `∑ diam(U_i)^s < η`.
      obtain ⟨U, hU₁, hU₂⟩ : ∃ U : ℕ → Set X, E ⊆ ⋃ i, U i ∧ ∀ i, EMetric.diam (U i) ≤ ENNReal.ofReal δ ∧ ∑' i, (EMetric.diam (U i)) ^ s < η := by
        contrapose! h;
        refine' ne_of_gt ( lt_of_lt_of_le hη₁ ( le_iInf fun U => le_iInf fun hU => le_iInf fun hU' => _ ) );
        obtain ⟨ i, hi ⟩ := h U hU;
        refine' le_trans ( hi ( hU' i ) ) _;
        refine' ENNReal.tsum_le_tsum fun n => _;
        by_cases h : ( U n ).Nonempty <;> simp +decide [ h ];
        simp_all +decide [ Set.not_nonempty_iff_eq_empty.mp h ];
      -- Since `η^(1/s) ≤ δ'`, for each `i`, `diam(U_i)^s ≤ ∑ diam(U_j)^s < η`, so `diam(U_i) < η^(1/s) ≤ δ'`.
      have h_diam_le : ∀ i, EMetric.diam (U i) ≤ ENNReal.ofReal δ' := by
        intro i
        have h_diam_le_i : (EMetric.diam (U i)) ^ s ≤ ∑' j, (EMetric.diam (U j)) ^ s := by
          exact?;
        refine' le_trans _ hη₂.2;
        exact le_trans ( by rw [ ← ENNReal.rpow_mul, mul_one_div_cancel hs.ne', ENNReal.rpow_one ] ) ( ENNReal.rpow_le_rpow ( h_diam_le_i.trans ( le_of_lt ( hU₂ i |>.2 ) ) ) ( by positivity ) );
      refine' le_trans ( ciInf_le _ _ ) _;
      exact ⟨ 0, Set.forall_mem_range.2 fun _ => zero_le _ ⟩;
      exact U;
      simp_all +decide [ ciInf_eq_ite ];
      refine' le_trans _ hη₂.1.le;
      refine' le_trans _ ( le_of_lt ( hU₂ 0 |>.2 ) );
      refine' ENNReal.tsum_le_tsum fun i => _;
      by_cases hi : ( U i ).Nonempty <;> simp +decide [ hi ]

/-
If the Hausdorff content is zero, the Hausdorff measure is zero.
-/
lemma hContent_zero_implies_hausdorffMeasure_zero {X : Type*} [EMetricSpace X] [MeasurableSpace X] [BorelSpace X]
    {s : ℝ} {δ : ℝ} {E : Set X} (hs : 0 < s) (hδ : 0 < δ)
    (h : hContent s δ E = 0) :
    MeasureTheory.Measure.hausdorffMeasure s E = 0 := by
      -- By Lemma 2, since the Hausdorff content of E at scale δ is zero, the Hausdorff measure of E at scale δ' is also zero.
      have h_zero_content : ∀ δ' > 0, hContent s δ' E = 0 := by
        exact?;
      simp +decide [ MeasureTheory.Measure.hausdorffMeasure_apply, h_zero_content ];
      intro i hi; specialize h_zero_content ( ENNReal.toReal i ) ; rcases eq_or_ne i ⊤ with rfl | hi' <;> simp_all +decide ;
      · refine' le_antisymm _ _;
        · refine' le_trans _ ( le_of_eq h );
          refine' le_iInf fun t => le_iInf fun ht => le_iInf fun h => _;
          exact iInf_le_of_le t ( iInf_le_of_le ht le_rfl );
        · exact zero_le _;
      · convert h_zero_content ( ENNReal.toReal_pos hi.ne' hi' ) using 1;
        unfold hContent; aesop;

/-
If the Hausdorff measure of E is finite, then the Hausdorff measure of E(delta, tau) is zero.
-/
lemma lemma_1e {X : Type*} [EMetricSpace X] [MeasurableSpace X] [BorelSpace X]
    (E : Set X) (s : ℝ) (δ : ℝ) (τ : ℝ) (hδ : 0 < δ) (hτ : 0 < τ) (hτ1 : τ < 1) (hs : 0 < s)
    (h_fin : MeasureTheory.Measure.hausdorffMeasure s E ≠ ⊤) :
    MeasureTheory.Measure.hausdorffMeasure s (E_delta_tau E s δ τ) = 0 := by
      convert hContent_zero_implies_hausdorffMeasure_zero hs hδ _;
      convert lemma_1d E s δ τ hδ hτ hτ1 hs _;
      refine' ne_of_lt ( lt_of_le_of_lt _ ( lt_top_iff_ne_top.mpr h_fin ) );
      refine' le_trans _ ( MeasureTheory.measure_mono _ );
      convert hContent_le_hausdorffMeasure hδ using 1;
      exact fun x hx => hx.1

/-
The set of points where the density is consistently low has measure zero.
-/
def E_star_tau {X : Type*} [EMetricSpace X] [MeasurableSpace X] [BorelSpace X]
    (E : Set X) (s : ℝ) (τ : ℝ) : Set X :=
  ⋃ n : ℕ, E_delta_tau E s (1 / (n + 1)) τ

lemma measure_E_star_tau_eq_zero {X : Type*} [EMetricSpace X] [MeasurableSpace X] [BorelSpace X]
    (E : Set X) (s : ℝ) (τ : ℝ) (hτ : 0 < τ) (hτ1 : τ < 1) (hs : 0 < s)
    (h_fin : MeasureTheory.Measure.hausdorffMeasure s E ≠ ⊤) :
    MeasureTheory.Measure.hausdorffMeasure s (E_star_tau E s τ) = 0 := by
      -- Apply `lemma_1e` to conclude that the Hausdorff measure of `E_star_tau E s τ` is zero.
      have h_star_zero : ∀ δ > 0, (MeasureTheory.Measure.hausdorffMeasure s) (E_delta_tau E s δ τ) = 0 := by
        exact?;
      convert MeasureTheory.measure_mono_null ( fun a ha => ?_ ) ( MeasureTheory.measure_iUnion_null fun n : ℕ => h_star_zero ( 1/ ( n+1 ) ) <| by positivity ) using 1;
      grind
