/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 03be0a39-7aaa-4d91-b00c-1966d5bf34f4

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define Hausdorff content and the set $E(\delta, \tau)$. We then prove four lemmas corresponding to the user's request.
1. `lemma1`: If the upper density is strictly less than $1/2^s$, then for small radii the density is bounded by $(1-\delta)/2^s$.
2. `lemma2`: If $x \in C$ with $|C| \le \delta$, then the Hausdorff content of $C \cap E$ is bounded by $(1-\delta)|C|^s$.
3. `lemma3_inclusion` and `lemma3_ae`: The set of points with small upper density is contained in a union of sets $E(1/k, 1-1/k)$, and consequently has Hausdorff measure 0 (i.e., the density is $\ge 1/2^s$ almost everywhere).
4. `hausdorffContent_le_hausdorffMeasure`: Hausdorff content is less than or equal to Hausdorff measure, which completes the lower bound proof.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of Hausdorff content and the set E(δ, τ).
-/
open Set MeasureTheory MeasureTheory.Measure ENNReal Metric Filter Topology

noncomputable def hausdorffContent {X : Type*} [MetricSpace X] (d : ℝ) : OuterMeasure X :=
  OuterMeasure.mkMetric'.pre (fun s ↦ (EMetric.diam s) ^ d) ⊤

noncomputable def E_set {X : Type*} [MetricSpace X] (E : Set X) (s : ℝ) (δ τ : ℝ) : Set X :=
  {x ∈ E | ∀ r, 0 < r → r ≤ δ → hausdorffContent s (Metric.ball x r ∩ E) ≤ ENNReal.ofReal (τ * (2 * r) ^ s)}

/-
If the limsup of the density is less than 1/2^s, then for small radii the density is bounded by (1-δ)/2^s.
-/
theorem lemma1 {X : Type*} [MetricSpace X] [MeasurableSpace X] [BorelSpace X]
    (E : Set X) (x : X) (s : ℝ) (hx : x ∈ E)
    (h : Filter.limsup (fun r ↦ hausdorffMeasure s (Metric.ball x r ∩ E) / (ENNReal.ofReal ((2 * r) ^ s))) (nhdsWithin 0 (Ioi 0)) < 1 / ENNReal.ofReal (2 ^ s)) :
    ∃ δ > 0, ∀ r, 0 < r → r ≤ δ →
      hausdorffMeasure s (Metric.ball x r ∩ E) / (ENNReal.ofReal ((2 * r) ^ s)) < (1 - ENNReal.ofReal δ) / ENNReal.ofReal (2 ^ s) := by
        -- By definition of limsup, there exists a δ > 0 such that for all 0 < r ≤ δ, the density is bounded above by (1 - δ)/2^s.
        obtain ⟨δ, hδ_pos, hδ⟩ : ∃ δ > 0, ∀ᶠ r in 𝓝[>] (0), (μH[s] (Metric.ball x r ∩ E)) / ENNReal.ofReal ((2 * r) ^ s) < (1 - ENNReal.ofReal δ) / ENNReal.ofReal (2 ^ s) := by
          -- By definition of limsup, there exists a δ > 0 such that for all 0 < r ≤ δ, the density is bounded above by (1 - δ)/2^s. Use this fact.
          obtain ⟨δ, hδ_pos, hδ⟩ : ∃ δ > 0, (1 - ENNReal.ofReal δ) / ENNReal.ofReal (2 ^ s) > Filter.limsup (fun r => (μH[s] (Metric.ball x r ∩ E)) / ENNReal.ofReal ((2 * r) ^ s)) (𝓝[>] 0) := by
            -- By definition of limsup, there exists a δ > 0 such that for all 0 < r ≤ δ, the density is bounded above by (1 - δ)/2^s. Use this fact to find such a δ.
            have hδ_exists : ∃ δ > 0, (1 - ENNReal.ofReal δ) / ENNReal.ofReal (2 ^ s) > Filter.limsup (fun r => (μH[s] (Metric.ball x r ∩ E)) / ENNReal.ofReal ((2 * r) ^ s)) (𝓝[>] 0) := by
              have hδ_aux : Filter.Tendsto (fun δ : ℝ => (1 - ENNReal.ofReal δ) / ENNReal.ofReal (2 ^ s)) (nhdsWithin 0 (Set.Ioi 0)) (nhds (1 / ENNReal.ofReal (2 ^ s))) := by
                refine' tendsto_nhdsWithin_of_tendsto_nhds _;
                refine' ENNReal.Tendsto.div_const _ _;
                · convert ENNReal.Tendsto.sub tendsto_const_nhds ( ENNReal.tendsto_ofReal ( Filter.tendsto_id ) ) _ using 1 <;> norm_num;
                · norm_num
              have := hδ_aux.eventually ( lt_mem_nhds h ) ; ( have := this.and self_mem_nhdsWithin; ( rcases this.exists with ⟨ δ, hδ₁, hδ₂ ⟩ ; exact ⟨ δ, hδ₂, hδ₁ ⟩ ; ) );
            exact hδ_exists;
          refine' ⟨ δ, hδ_pos, _ ⟩;
          rw [ Filter.limsup_eq ] at hδ;
          rw [ gt_iff_lt, lt_iff_not_ge ] at hδ;
          simp +zetaDelta at *;
          exact hδ.choose_spec.1.mono fun r hr => lt_of_le_of_lt hr hδ.choose_spec.2;
        obtain ⟨δ', hδ'_pos, hδ'⟩ : ∃ δ' > 0, ∀ r, 0 < r → r < δ' → (μH[s] (Metric.ball x r ∩ E)) / ENNReal.ofReal ((2 * r) ^ s) < (1 - ENNReal.ofReal δ) / ENNReal.ofReal (2 ^ s) := by
          rcases mem_nhdsGT_iff_exists_Ioo_subset.mp hδ with ⟨ δ', hδ'_pos, hδ' ⟩ ; use δ' ; aesop;
        refine' ⟨ Min.min δ' δ / 2, _, _ ⟩ <;> try linarith [ lt_min hδ'_pos hδ_pos ] ;
        intro r hr₁ hr₂; specialize hδ' r hr₁ ( by linarith [ min_le_left δ' δ, min_le_right δ' δ ] ) ; refine' lt_of_lt_of_le hδ' _ ; gcongr ; linarith [ min_le_left δ' δ, min_le_right δ' δ ] ;

/-
If x ∈ C with |C| ≤ δ, then the Hausdorff content of C ∩ E is bounded by (1 - δ)|C|^s.
-/
theorem lemma2 {X : Type*} [MetricSpace X] [MeasurableSpace X] [BorelSpace X]
    (E : Set X) (x : X) (s : ℝ) (δ : ℝ) (C : Set X)
    (hx : x ∈ C) (hC_diam : EMetric.diam C ≤ ENNReal.ofReal δ)
    (h_subset : C ⊆ Metric.ball x (ENNReal.toReal (EMetric.diam C)))
    (h_density : ∀ r, 0 < r → r ≤ δ → hausdorffMeasure s (Metric.ball x r ∩ E) ≤ ENNReal.ofReal ((1 - δ) * r ^ s)) :
    hausdorffMeasure s (C ∩ E) ≤ hausdorffMeasure s (Metric.ball x (ENNReal.toReal (EMetric.diam C)) ∩ E) ∧
    hausdorffMeasure s (Metric.ball x (ENNReal.toReal (EMetric.diam C)) ∩ E) ≤ ENNReal.ofReal ((1 - δ) * (ENNReal.toReal (EMetric.diam C)) ^ s) := by
      exact ⟨ MeasureTheory.measure_mono <| Set.inter_subset_inter h_subset <| Set.Subset.refl _, if hC_diam_pos : 0 < ( EMetric.diam C |> ENNReal.toReal ) then h_density _ hC_diam_pos ( by
        convert ENNReal.toReal_mono _ hC_diam;
        · rw [ ENNReal.toReal_ofReal ];
          exact le_of_not_gt fun h => by rw [ ENNReal.ofReal_eq_zero.mpr h.le ] at hC_diam; exact hC_diam_pos.ne' ( by simp +decide [ show EMetric.diam C = 0 from le_antisymm ( hC_diam.trans ( by simp +decide ) ) ( zero_le _ ) ] ) ;
        · exact ENNReal.ofReal_ne_top ) else by simp +decide [ show ( EMetric.diam C |> ENNReal.toReal ) = 0 from le_antisymm ( le_of_not_gt hC_diam_pos ) ( ENNReal.toReal_nonneg ) ] ⟩

/-
The set of points with small upper density is contained in the union of E(1/k, 1-1/k).
-/
theorem lemma3_inclusion {X : Type*} [MetricSpace X] [MeasurableSpace X] [BorelSpace X]
    (E : Set X) (s : ℝ) (hs : 0 ≤ s) :
    {x ∈ E | Filter.limsup (fun r ↦ hausdorffMeasure s (Metric.ball x r ∩ E) / (ENNReal.ofReal ((2 * r) ^ s))) (nhdsWithin 0 (Ioi 0)) < 1 / ENNReal.ofReal (2 ^ s)} ⊆
    ⋃ (k : ℕ), E_set E s (1 / (k + 1 : ℝ)) (1 - 1 / (k + 1 : ℝ)) := by
      intro x hx
      obtain ⟨hx_E, h_density⟩ := hx
      obtain ⟨δ, hδ_pos, hδ⟩ : ∃ δ > 0, ∀ r, 0 < r → r ≤ δ → (hausdorffMeasure s (Metric.ball x r ∩ E)) / (ENNReal.ofReal ((2 * r) ^ s)) < (1 - ENNReal.ofReal δ) / ENNReal.ofReal (2 ^ s) := by
        convert lemma1 E x s hx_E h_density using 1
      obtain ⟨k, hk⟩ : ∃ k : ℕ, 1 / (k + 1) < δ := by
        exact exists_nat_one_div_lt hδ_pos |> fun ⟨ k, hk ⟩ => ⟨ k, by simpa using hk ⟩
      have hE_set : x ∈ E_set E s (1 / (k + 1)) (1 - 1 / (k + 1)) := by
        refine' ⟨ hx_E, fun r hr₁ hr₂ => _ ⟩;
        -- By definition of $E(1/k, 1-1/k)$, we have $hausdorffContent s (Metric.ball x r ∩ E) \leq (1 - 1/(k+1)) * (2r)^s$.
        have h_content : hausdorffMeasure s (Metric.ball x r ∩ E) ≤ ENNReal.ofReal ((1 - 1 / (k + 1)) * (2 * r) ^ s) := by
          have h_content : (hausdorffMeasure s (Metric.ball x r ∩ E)) / (ENNReal.ofReal ((2 * r) ^ s)) < (1 - ENNReal.ofReal (1 / (k + 1))) / ENNReal.ofReal (2 ^ s) := by
            refine' lt_of_lt_of_le ( hδ r hr₁ ( hr₂.trans hk.le ) ) _;
            gcongr;
          rw [ ENNReal.lt_div_iff_mul_lt ] at h_content <;> norm_num at *;
          · rw [ ENNReal.ofReal_mul ( sub_nonneg.2 <| inv_le_one_of_one_le₀ <| by linarith ) ];
            rw [ ENNReal.ofReal_sub ] <;> norm_num;
            · rw [ ← ENNReal.div_le_iff_le_mul ];
              · refine' le_trans _ h_content.le;
                refine' le_mul_of_one_le_right _ _;
                · exact zero_le _;
                · exact le_trans ( by norm_num ) ( ENNReal.ofReal_le_ofReal ( Real.one_le_rpow ( by norm_num ) hs ) );
              · exact Or.inl <| ne_of_gt <| ENNReal.ofReal_pos.mpr <| by positivity;
              · exact Or.inl ENNReal.ofReal_ne_top;
            · positivity;
          · exact Or.inl ( by positivity );
        refine' le_trans _ h_content;
        simp +decide [ MeasureTheory.Measure.hausdorffMeasure_apply ];
        refine' le_iSup_of_le ⊤ _;
        simp +decide [ hausdorffContent ];
        intro i hi;
        refine' le_trans ( iInf_le _ _ ) _;
        exact i;
        simp +decide [ hi, MeasureTheory.extend ]
      exact Set.mem_iUnion_of_mem k hE_set

/-
The set of points where the upper density is less than 1/2^s has Hausdorff measure 0.
-/
theorem lemma3_ae {X : Type*} [MetricSpace X] [MeasurableSpace X] [BorelSpace X]
    (E : Set X) (s : ℝ) (hs : 0 ≤ s)
    (h_null : ∀ k : ℕ, hausdorffMeasure s (E_set E s (1 / (k + 1 : ℝ)) (1 - 1 / (k + 1 : ℝ))) = 0) :
    hausdorffMeasure s {x ∈ E | Filter.limsup (fun r ↦ hausdorffMeasure s (Metric.ball x r ∩ E) / (ENNReal.ofReal ((2 * r) ^ s))) (nhdsWithin 0 (Ioi 0)) < 1 / ENNReal.ofReal (2 ^ s)} = 0 := by
      convert MeasureTheory.measure_mono_null _ ( MeasureTheory.measure_iUnion_null fun k => h_null k );
      convert lemma3_inclusion E s hs using 1

/-
Since $H_\infty^S (B_r(x)\cap E)\le H^s(B_r(x)\cap E)$ holds, (3.1) finishes the proof of lower bound.
-/
theorem hausdorffContent_le_hausdorffMeasure {X : Type*} [MetricSpace X] [MeasurableSpace X] [BorelSpace X]
    (s : ℝ) (A : Set X) :
    hausdorffContent s A ≤ hausdorffMeasure s A := by
      rw [ MeasureTheory.Measure.hausdorffMeasure ];
      refine' le_trans _ ( MeasureTheory.le_toMeasure_apply _ _ _ );
      refine' le_trans _ ( ciInf_le_of_le _ _ _ );
      rotate_left;
      exact Set X;
      refine' fun _ => ( MeasureTheory.OuterMeasure.mkMetric fun ( r : ℝ≥0∞ ) => r ^ s ) A;
      · exact ⟨ 0, Set.forall_mem_range.2 fun _ => zero_le _ ⟩;
      · exact A;
      · rfl;
      · simp +decide [ hausdorffContent ];
        simp +decide [ MeasureTheory.OuterMeasure.mkMetric', MeasureTheory.OuterMeasure.mkMetric ];
        refine' le_iSup_of_le ⊤ _;
        simp +decide [ MeasureTheory.OuterMeasure.mkMetric'.pre ]
